server:
  port: 8081
spring:
  main:
    banner-mode: off
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/batch_job
    username: root
    password: dudkrish1A
  jpa:
    hibernate:
      ddl-auto=none:
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true

csv:
  read:
    gitHubUrl: https://raw.githubusercontent.com/harilearning1989/DataFiles/master/
    windPrefix: D:/DataFiles/Downloaded/
    linuxPrefix: /home/hari/MyWork/DataFiles/
    macPrefix: /Users/hariduddukunta/MyWork/DataFiles/